### ISSUE TITLE
Heheheh - Traceback in `raw_title_untranslated` of http.py

### ISSUE THREAD

**Issue by AbstractUmbra** [kaylynn234/nhentaio#1]
```py
Traceback (most recent call last):
  File "/home/penumbra/.cache/pypoetry/virtualenvs/okayu-Ypw0CF8H-py3.9/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/penumbra/projects/personal/okayu/cogs/lewd.py", line 291, in nhentai
    gallery: Optional[nhentaio.Gallery] = await self.bot.hentai_client.fetch_gallery(hentai_id)
  File "/home/penumbra/.cache/pypoetry/virtualenvs/okayu-Ypw0CF8H-py3.9/lib/python3.9/site-packages/nhentaio/client.py", line 74, in fetch_gallery
    return await self._state.gallery_from(response, id)
  File "/home/penumbra/.cache/pypoetry/virtualenvs/okayu-Ypw0CF8H-py3.9/lib/python3.9/site-packages/nhentaio/http.py", line 106, in gallery_from
    raw_title_untranslated = filter(None, (element.text for element in tree.xpath(f"{TITLE_PREFIX}/h2")[0]))
IndexError: list index out of range
```

Hello - traceback is as you see it, I assume this means there is no translated name for the given [gallery](https://nhentai.to/g/177013)?

Let me know if you need any more info.

**Comment by kaylynn234** [comment]
This has been fixed in 0.3.0. You can read the changelog [here](https://nhentaio.readthedocs.io/changelog.html).

Note that 0.3.0 changes attribute names since that felt like a better reflection of what nhentai actually displays.
